### ISSUE TITLE
onSuccess callback should be on the main thread

### ISSUE THREAD

**Issue by aurynn** [alwaysallthetime/ADNLib#3]
Hey;

I wanted to check with you guys before I implemented this, but shouldn't the onSuccess callback fire on the main thread using onPostExecute, so I can access the view hierarchy with the results?

Or, am I approaching this completely backwards? :)

**Comment by rrbrambley** [comment]
I have questioned the currently implementation as well. So currently, if you need to access the UI thread, you can use a [Handler](http://developer.android.com/reference/android/os/Handler.html). If you're in an Activity, you could create a new one in onCreate() (so that it would be created on the correct thread), and then do something like:

```
@Override
public void onSuccess(Message responseData) {
    mHandler.post(new Runnable() {
        @Override
        public void run() {
            //do my UI work here.
        }
    }
}
```

However, there is probably a good argument to be made about making AppDotNetClientTask use onPostExecute() instead. If you have a proposal, feel free to send a pull request and I'll take a look.

Though, I should add: do we really want all callbacks to fire on the UI thread? If there is some processing to do with the data (e.g. persisting data with sqlite), might we want to continue doing so on the other thread?

@derelk designed the client tasks, so I am unsure about why he made this exact decision.
